[project]
name = "aircraft-digital-twin"
version = "0.1.0"
description = "Aircraft Digital Twin with PPO-based Predictive Maintenance using NASA CMAPSS"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "numpy",
    "pandas",
    "scikit-learn",
    "tensorflow",
    "gymnasium",
    "stable-baselines3",
    "simpy",
    "matplotlib",
    "seaborn",
    "ipykernel",
    "tensorboard",
    "pygame",
    "mlflow>=3.12.0",
]

[tool.setuptools]
packages = ["scripts"]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"
